//
// Created by henri on 03/04/23.
//

#ifndef AB_ADJUSTABLEROBUSTOPTIMIZATIONWITHOBJECTIVEUNCERTAINTY_TOLERANCES_H
#define AB_ADJUSTABLEROBUSTOPTIMIZATIONWITHOBJECTIVEUNCERTAINTY_TOLERANCES_H

#define TOLERANCE_FOR_CONTINUOUS_VARIABLES 1e-3
#define TOLERANCE_FOR_ACTIVE_COLUMNS 1e-4

#endif //AB_ADJUSTABLEROBUSTOPTIMIZATIONWITHOBJECTIVEUNCERTAINTY_TOLERANCES_H
